# Generated by Django 3.1.1 on 2020-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_img_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='category_img',
            field=models.CharField(default='', max_length=40),
        ),
    ]
