# Generated by Django 3.1.1 on 2020-10-04 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201004_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time_ago',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
