# Generated by Django 3.1.1 on 2020-09-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0005_auto_20200918_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
