# Generated by Django 3.1.1 on 2020-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0006_remove_post_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('title_tag', models.TextField()),
                ('pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
