# Generated by Django 3.1.1 on 2020-10-23 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0008_auto_20200926_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admmessage',
            name='title_tag',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
