# Generated by Django 3.1.1 on 2020-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0003_auto_20201003_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
